apiVersion: apps/v1
kind: Deployment
metadata :
  name: mavenwebappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  template:
     metadata:
       name: mavenwebapp             # for pod name
       labels:
         app: mavenwebapp
     spec:
       containers:
       - name: mavenwebappcontainer
         image: vasudockerhubacc/maven-web-application:1
         ports:
         - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  type: NodePort
  selector:
    app: mavenwebappp
  ports:
  - port: 80
    targetPort: 8080
